version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    container_name: db-container1
    environment:
        - DATABASE_HOST=127.0.0.1
        - POSTGRES_DB=bacesita2
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports: 
      - "80:80"
    depends_on:
      - postgres


volumes:
  postgres_data:
